### ISSUE TITLE
Stop messing with UX

### ISSUE THREAD

**Issue by extrowerk** [privacypass/privacypass.github.io#2]
For god sake, why on earth do you messing with scrolling on the page?
Have you *EVER* tested it on touch enabled devices?
Why the font size changes if i tap the display to scroll?
Is this a usability joke or do you want to torture the visitors?
Why does your page using js at all?
This is BS.

**Comment by alxdavids** [comment]
I'm not sure what this is referring to? It's a pretty standard Github pages setup with no additional JS beyond what is present in the theme already. Maybe you want to take it up with the theme owner instead?
